#!/bin/bash
# Runs INSIDE the sandbox: proves lib/install-release.sh with a fake systemctl and a real
# tarball, generated by tools/build-release.py. Exits with the number of failures.
#
#   run-release.sh <repo-mounted-at-/repo>
#
# What is at stake: that script swaps the production code. A mistake there gives no syntax
# error nor fails any test -- it publishes the wrong version, or publishes and cannot
# go back. Since there is no shell test in the repository, this is the proof.
set -u
REPO="${1:-/repo}"
APP_DIR=/opt/gamepanel
INSTALLER="$REPO/lib/install-release.sh"
failures=0

ok()   { printf 'OK        %s\n' "$*"; }
fail() { printf 'FALHOU    %s\n' "$*"; failures=$((failures + 1)); }
check() { # description, expected, actual
  if [ "$2" = "$3" ]; then ok "$1"; else fail "$1 (esperado '$2', veio '$3')"; fi
}
has()     { if [ -e "$2" ]; then ok "$1"; else fail "$1 (nao existe: $2)"; fi; }
has_not() { if [ -e "$2" ]; then fail "$1 (ainda existe: $2)"; else ok "$1"; fi; }

install_release() { # tarball, [health command]
  local tarball="$1" health="${2:-}"
  local checksum
  checksum="$(sha256sum "$tarball" | cut -d' ' -f1)"
  bash "$INSTALLER" gamepanel "$tarball" "$checksum" "$APP_DIR" gamepanel.service "$health"
}

version_of() { # tarball -> the VERSION from the stamp
  tar -xzOf "$1" gamepanel/_build.py | sed -n "s/^VERSION = '\\(.*\\)'\$/\\1/p"
}

# ----- the artifact, built by the real packager -----
work=$(mktemp -d)
python3 "$REPO/tools/build-release.py" gamepanel --out "$work/dist" >/dev/null 2>&1 \
  || { fail "build-release.py nao gerou o pacote"; exit 1; }
tarball="$(ls "$work"/dist/gamepanel-*.tar.gz)"
version="$(version_of "$tarball")"
ok "empacotou ${version}"

# Determinism: the same code must give the same file, otherwise the sha256 only answers
# "did it arrive whole?" instead of "is it really this code?".
first_sum="$(sha256sum "$tarball" | cut -d' ' -f1)"
python3 "$REPO/tools/build-release.py" gamepanel --out "$work/dist2" >/dev/null 2>&1
second_sum="$(sha256sum "$work"/dist2/gamepanel-*.tar.gz | cut -d' ' -f1)"
check "empacotar duas vezes da o mesmo sha256" "$first_sum" "$second_sum"

# ----- the CT, with the OLD layouts in place -----
# There are THREE different shapes, because each previous version left its own, and all were
# found on the real CTs when publishing (300 and 301):
#   a) ${APP_DIR}/<package>/ -- the layout right before per-version releases;
#   b) loose .py + templates/ and static/ at the root -- the panel before the package;
#   c) a folder with the package's OLD NAME (broker/) -- the broker before the rename.
# (b) and (c) are the ones that matter: old-named code, alive and importable in the container.
mkdir -p "$APP_DIR/gamepanel/templates"
echo "# versao anterior a este mecanismo" > "$APP_DIR/gamepanel/app.py"
mkdir -p "$APP_DIR/templates" "$APP_DIR/static/css" "$APP_DIR/broker"
echo "# painel antes do pacote"  > "$APP_DIR/app.py"
echo "# nome em portugues"       > "$APP_DIR/busca_de_jogos.py"
echo "# pacote antes do rename"  > "$APP_DIR/broker/nucleo.py"
echo "<!-- tela velha -->"       > "$APP_DIR/templates/base.html"
# lib/ and games/ are NOT the package: provisioning pushes them separately and they stay.
mkdir -p "$APP_DIR/lib" "$APP_DIR/games"
echo "# fases"    > "$APP_DIR/lib/ct-phases.sh"
echo "APP_ID=730" > "$APP_DIR/games/exemplo.env"

# ----- 1. wrong sha publishes nothing -----
out="$(bash "$INSTALLER" gamepanel "$tarball" \
       "0000000000000000000000000000000000000000000000000000000000000000" \
       "$APP_DIR" gamepanel.service 2>&1)"
check "sha errado sai com erro" "1" "$?"
case "$out" in *"sha256 nao confere"*) ok "sha errado diz o motivo";;
               *) fail "sha errado nao explicou (saida: $out)";; esac
has_not "sha errado nao deixou release" "$APP_DIR/releases"

# ----- 2. normal install -----
install_release "$tarball" >/dev/null 2>&1
check "instalacao normal termina bem" "0" "$?"
has "a pasta da versao existe"   "$APP_DIR/releases/$version/gamepanel/app.py"
has "templates vieram junto"     "$APP_DIR/releases/$version/gamepanel/templates/base.html"
has "blueprints vieram junto"    "$APP_DIR/releases/$version/gamepanel/blueprints/servers.py"
has "o carimbo esta no lugar"    "$APP_DIR/releases/$version/gamepanel/_build.py"
check "current aponta para a versao" "$APP_DIR/releases/$version" "$(readlink -f $APP_DIR/current)"
has_not "o layout antigo foi embora"  "$APP_DIR/gamepanel"
has_not "os .py soltos foram embora"     "$APP_DIR/app.py"
has_not "o .py de nome velho foi embora" "$APP_DIR/busca_de_jogos.py"
has_not "templates/ da raiz foi embora"  "$APP_DIR/templates"
has_not "static/ da raiz foi embora"     "$APP_DIR/static"
has_not "a pasta do nome velho do pacote foi embora" "$APP_DIR/broker"
has "lib/ do provisionamento fica"   "$APP_DIR/lib/ct-phases.sh"
has "games/ do provisionamento fica" "$APP_DIR/games/exemplo.env"
has_not "nao sobrou pasta temporaria" "$(ls -d $APP_DIR/.staging.* 2>/dev/null | head -1)"
if grep -q "systemctl restart gamepanel.service" /var/log/fake-calls.log 2>/dev/null
  then ok "reiniciou o servico"; else fail "nao reiniciou o servico"; fi

# ----- 3. new version: the previous one stays, the symlink moves -----
# Copy of the repo with another VERSION, to simulate the next deploy without touching the original.
declared_version="$(cat "$REPO/VERSION")"
fake_repo=$(mktemp -d); cp -r "$REPO"/. "$fake_repo"/ 2>/dev/null
echo "9.9.9" > "$fake_repo/VERSION"
python3 "$fake_repo/tools/build-release.py" gamepanel --out "$work/dist3" >/dev/null 2>&1
next_tarball="$(ls "$work"/dist3/gamepanel-*.tar.gz)"
next_version="$(version_of "$next_tarball")"
install_release "$next_tarball" >/dev/null 2>&1
check "a versao seguinte instala" "0" "$?"
check "current andou para a nova" "$APP_DIR/releases/$next_version" "$(readlink -f $APP_DIR/current)"
has "a anterior continua no disco" "$APP_DIR/releases/$version/gamepanel/app.py"
case "$declared_version" in 9.9.9) fail "o VERSION do repo foi alterado";;
                            *) ok "o repo nao foi tocado";; esac

# ----- 4. a service that does not come up goes back to the previous one -----
# Fake systemctl that answers "inactive": the case of a release that breaks on start.
cat > /usr/local/sbin/systemctl <<'FALSO'
#!/bin/bash
echo "systemctl $*" >> /var/log/fake-calls.log
case "$1" in is-active) exit 3;; esac
FALSO
chmod +x /usr/local/sbin/systemctl
before="$(readlink -f $APP_DIR/current)"
echo "8.8.8" > "$fake_repo/VERSION"
python3 "$fake_repo/tools/build-release.py" gamepanel --out "$work/dist4" >/dev/null 2>&1
broken_tarball="$(ls "$work"/dist4/gamepanel-8.8.8*.tar.gz 2>/dev/null | head -1)"
out="$(install_release "$broken_tarball" 2>&1)"
check "release que nao sobe sai com erro" "1" "$?"
check "current voltou para a anterior" "$before" "$(readlink -f $APP_DIR/current)"
case "$out" in *"voltando para"*) ok "o rollback aparece na saida";;
               *) fail "o rollback nao foi anunciado (saida: $out)";; esac

echo
if [ "$failures" -eq 0 ]; then echo "Tudo certo."; else echo "$failures verificacao(oes) falharam."; fi
exit "$failures"
