#!/bin/bash
case "${1:-}" in
  available) echo "system  debian-13-standard_13.1-2_amd64.tar.zst" ;;
  list)      printf '%s:vztmpl/debian-13-standard_13.1-2_amd64.tar.zst debian-13-standard_13.1-2_amd64.tar.zst\n%s:vztmpl/debian-13-standard_13.6-1_amd64.tar.zst debian-13-standard_13.6-1_amd64.tar.zst\n' "${2:-local}" "${2:-local}" ;;
esac
