#!/usr/bin/env bash
# Installs a game INSIDE the container itself (local transport). It is what the broker runs over
# SSH after creating the CT: it sends this file, ct-phases.sh and an install.env, and executes
#
#     bash ct-install.sh install.env
#
# The phases are the SAME as the manual deploy's (lib/ct-phases.sh, also loaded by
# provision-game-lxc.sh on the Proxmox host); only the transport changes: there it is `pct exec`,
# here a local `bash -lc`. install.env is generated by the broker with every value quoted (it is
# never concatenated into a command line), and never carries Steam account credentials.
set -Eeuo pipefail
IFS=$'\n\t'

INSTALL_ENV="${1:?usage: ct-install.sh <install.env>}"
SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"

STEAMCMD_URL="https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz"
STEAMCMD_DIR="/opt/steamcmd"
GAME_DIR="/opt/game"

msg() { printf '\n[%s] %s\n' "$(date +%H:%M:%S)" "$*"; }
warn() { printf '\n[WARN] %s\n' "$*" >&2; }
die() { printf '\n[ERROR] %s\n' "$*" >&2; exit 1; }

on_error() {
  local cmd="$2"
  # The failed command may be the SteamCMD line carrying the Steam account password
  [[ -n "${STEAM_PASS:-}" ]] && cmd="${cmd//${STEAM_PASS}/******}"
  die "Installation failed at line ${1} running: ${cmd}"
}
trap 'on_error "${LINENO}" "${BASH_COMMAND}"' ERR

# LOCAL transport for the phases (the host's is `pct exec CT -- bash -lc`).
run_ct() {
  bash -lc "$1"
}

push_file_to_ct() {
  local src="$1"
  local dest="$2"
  local mode="${3:-0644}"
  install -D -m "$mode" "$src" "$dest"
}

# Same shortcut as provision-game-lxc.sh: /usr/local/bin + a symlink in /usr/bin, because the
# PATH of a non-login session does not include /usr/local/bin.
install_helper() {
  local name="$1"
  local src="$2"
  push_file_to_ct "$src" "/usr/local/bin/${name}" 0755
  run_ct "ln -sfn /usr/local/bin/${name} /usr/bin/${name}"
}

FIREWALL_SCRIPT="${SCRIPT_DIR}/ct-firewall.sh"
PANEL_ACCESS_SCRIPT="${SCRIPT_DIR}/ct-panel-access.sh"
LIB_FASES="${SCRIPT_DIR}/ct-phases.sh"
[[ -f "$LIB_FASES" ]] || die "ct-phases.sh not found next to $0"
[[ -f "$INSTALL_ENV" ]] || die "Environment file not found: $INSTALL_ENV"
set -a
# shellcheck disable=SC1090
source "$INSTALL_ENV"
set +a
# shellcheck source=lib/ct-phases.sh
source "$LIB_FASES"

main() {
  resolve_game_variables
  install_base_packages_in_ct
  ensure_steam_user
  setup_panel_access
  install_steamcmd_in_ct
  setup_windows_runtime
  run_pre_install
  install_game_in_ct
  # post-install runs before detection because a game may CREATE its own start script
  run_post_install
  apply_recipes
  detect_start_script
  render_update_helper
  render_update_checker
  render_service_helpers
  render_systemd_unit
  start_game_service
  setup_firewall
  # No lock_root_login here: the broker is logged in as root right now, and it locks root in the
  # same final command that removes its own key (gamebroker/runtime/ssh_installer.py, _cleanup).
  # The line the broker looks for: without it, exit 0 is not enough to consider the install done.
  msg "INSTALACAO CONCLUIDA: ${GAME_DISPLAY_NAME} (${SERVICE_NAME})"
}

main "$@"
