"""Sugestoes de jogo tiradas dos eggs do Pterodactyl — GERADO, NAO EDITE.

Gerado por tools/import-pterodactyl.py (pelican-eggs/games-steamcmd, MIT). Para atualizar,
rode o script e revise o diff. SUGGESTIONS sao jogos que o LinuxGSM, a lista manual e os
curados nao tem; COMPLEMENTS sao os campos vazios de uma sugestao do LinuxGSM que o egg
preenche (por App ID). Tudo aqui ja passou pelo validador do broker na geracao.
"""
SOURCE = "Pterodactyl eggs (MIT), gerado em 2026-09-28"

SUGGESTIONS = (
    {'appid': 2934900,
     'name': 'Astro Colony',
     'key': 'astro-colony',
     'ports': '7777/udp 27015/udp',
     'game_port': 7777,
     'query_port': 27015,
     'extra_port': 0,
     'start_script': 'AstroColony/Binaries/Linux/AstroColonyServer',
     'start_args': '-log -QueryPort={QUERY_PORT}',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '/opt/game/AstroColony/Saved/Config/LinuxServer',
     'config_files': ['/opt/game/AstroColony/Saved/Config/LinuxServer/ServerSettings.ini'],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'astro_colony' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Removi do comando o que o painel nao passa (SteamServerName): nome, senha, IP e afins. '
                  'Acrescente o que faltar.']},
    {'appid': 728470,
     'name': 'Astroneer',
     'key': 'astroneer',
     'ports': '27000/udp',
     'game_port': 27000,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'Astro/Binaries/Win64/AstroServer-Win64-Shipping.exe',
     'start_args': '',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '/opt/game/Astro/Saved/Config/WindowsServer',
     'config_files': ['/opt/game/Astro/Saved/Config/WindowsServer/Engine.ini',
                      '/opt/game/Astro/Saved/Config/WindowsServer/AstroServerSettings.ini'],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'astroneer' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.']},
    {'appid': 3017590,
     'name': 'Brickadia',
     'key': 'brickadia',
     'ports': '',
     'game_port': 0,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'Brickadia/Binaries/Linux/BrickadiaServer-Linux-Shipping',
     'start_args': '-port={PORT}',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'brickadia' do Pterodactyl: confira antes de enviar.",
                  'O README do egg nao lista a porta padrao: preencha as portas.',
                  'Removi do comando o que o painel nao passa (token): nome, senha, IP e afins. Acrescente o que '
                  'faltar.',
                  'O comando do egg encadeava outros comandos (;, |, &&): so o do jogo ficou.']},
    {'appid': 489650,
     'name': 'Citadel: Forged with Fire',
     'key': 'citadel-forged-with-fire',
     'ports': '7777/udp 27015/udp',
     'game_port': 7777,
     'query_port': 27015,
     'extra_port': 0,
     'start_script': 'CitadelServer.sh',
     'start_args': '',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '/opt/game/Config',
     'config_files': ['/opt/game/Config/Game.ini'],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'citadel' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.']},
    {'appid': 1061710,
     'name': 'CryoFall',
     'key': 'cryofall',
     'ports': '6000/udp',
     'game_port': 6000,
     'query_port': 0,
     'extra_port': 0,
     'start_script': '',
     'start_args': '',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'cryofall' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  "O egg sobe o jogo por 'dotnet', que o broker nao chama: preencha o script de start e os "
                  'argumentos a mao.']},
    {'appid': 3858450,
     'name': 'Cubic Odyssey',
     'key': 'cubic-odyssey',
     'ports': '27001/udp',
     'game_port': 27001,
     'query_port': 0,
     'extra_port': 0,
     'start_script': '',
     'start_args': '',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'cubic_odyssey' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'O egg nao diz qual e o executavel: preencha o script de start.']},
    {'appid': 412220,
     'name': 'DDNet',
     'key': 'ddnet',
     'ports': '8303/udp',
     'game_port': 8303,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'ddnet/DDNet-Server',
     'start_args': '',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'ddnet' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.']},
    {'appid': 2584780,
     'name': 'Dead Matter',
     'key': 'dead-matter',
     'ports': '7001/udp 7002/udp',
     'game_port': 7001,
     'query_port': 7002,
     'extra_port': 0,
     'start_script': 'DeadMatter/Binaries/Win64/DeadMatterServer-Win64-Test.exe',
     'start_args': '-port={PORT} -queryport={QUERY_PORT}',
     'shiftable': True,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'dead_matter' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'Removi do comando o que o painel nao passa (SteamServerName): nome, senha, IP e afins. '
                  'Acrescente o que faltar.']},
    {'appid': 530870,
     'name': 'Empyrion: Galactic Survival',
     'key': 'empyrion-galactic-surviv',
     'ports': '27015/udp',
     'game_port': 27015,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'empyrion/DedicatedServer/EmpyrionDedicated.exe',
     'start_args': '-batchmode -log -logFile ./logs/current.log',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'empyrion' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.']},
    {'appid': 2915550,
     'name': 'Foundry',
     'key': 'foundry',
     'ports': '3724/udp 27015/udp',
     'game_port': 3724,
     'query_port': 27015,
     'extra_port': 0,
     'start_script': 'FoundryDedicatedServer.exe',
     'start_args': '-log',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton', 'xvfb'],
     'config_path': '/opt/game',
     'config_files': ['/opt/game/App.cfg'],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'foundry' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.']},
    {'appid': 476400,
     'name': 'Ground Branch',
     'key': 'ground-branch',
     'ports': '7777/udp 27015/udp',
     'game_port': 7777,
     'query_port': 27015,
     'extra_port': 0,
     'start_script': 'GroundBranch/Binaries/Win64/GroundBranchServer-Win64-Shipping.exe',
     'start_args': 'MultiHome=0.0.0.0 Port={PORT} -log',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '/opt/game/GroundBranch/ServerConfig',
     'config_files': ['/opt/game/GroundBranch/ServerConfig/Server.ini',
                      '/opt/game/GroundBranch/Config/DefaultModding.ini'],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'ground_branch' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.']},
    {'appid': 1424230,
     'name': 'Holdfast NaW',
     'key': 'holdfast-naw',
     'ports': '20100/udp 27000/udp 8700/udp',
     'game_port': 20100,
     'query_port': 27000,
     'extra_port': 8700,
     'start_script': '',
     'start_args': '',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'holdfast' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'O executavel do egg (./holdfastnaw-dedicated/Holdfast NaW) nao cabe no broker: preencha o '
                  'script de start.',
                  'Removi do comando o que o painel nao passa (framerate): nome, senha, IP e afins. Acrescente o '
                  'que faltar.',
                  'O broker recusaria start_args; deixei em branco.']},
    {'appid': 1118810,
     'name': 'Midnight Ghost Hunt',
     'key': 'midnight-ghost-hunt',
     'ports': '7777/udp 27015/udp 7787/udp',
     'game_port': 7777,
     'query_port': 27015,
     'extra_port': 7787,
     'start_script': 'MidnightGhostHunt/Binaries/Win64/MidnightGhostHuntServer-Win64-Shipping.exe',
     'start_args': '-server -log -port={PORT} -queryport={QUERY_PORT} -BeaconPort={EXTRA_PORT} '
                   '-multihome=0.0.0.0 -Map=Asylum -BotDifficulty=Auto',
     'shiftable': True,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'midnight_ghost_hunt' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'Removi do comando o que o painel nao passa (Gamemode, Gamename, Region, password): nome, '
                  'senha, IP e afins. Acrescente o que faltar.']},
    {'appid': 1549820,
     'name': 'Modiverse',
     'key': 'modiverse',
     'ports': '7777/udp 27015/udp',
     'game_port': 7777,
     'query_port': 27015,
     'extra_port': 0,
     'start_script': 'KJMod/Binaries/Linux/KJModServer',
     'start_args': '-port={PORT} -queryport={QUERY_PORT} -KJModBaseUGCFolder=ServerData -DoNotRestartOnEmpty '
                   '-InitUGCs -maxplayers=128',
     'shiftable': True,
     'platform': '',
     'recipes': [],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'modiverse' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Removi do comando o que o painel nao passa (SteamServerName): nome, senha, IP e afins. '
                  'Acrescente o que faltar.']},
    {'appid': 1863440,
     'name': 'Mount & Blade II: Bannerlord',
     'key': 'mount-blade-ii-bannerlor',
     'ports': '7210/udp',
     'game_port': 7210,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'bin/Win64_Shipping_Server/DedicatedCustomServer.Starter.exe',
     'start_args': '/port {PORT} /dedicatedcustomserverconfigfile tdm_config.txt',
     'shiftable': True,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'mount_blade_II_bannerlord' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'Removi do comando o que o painel nao passa (dedicatedcustomserverauthtoken): nome, senha, IP '
                  'e afins. Acrescente o que faltar.']},
    {'appid': 1794810,
     'name': 'Myth of Empires',
     'key': 'myth-of-empires',
     'ports': '11888/udp 12888/udp',
     'game_port': 11888,
     'query_port': 12888,
     'extra_port': 0,
     'start_script': 'MOE/Binaries/Win64/MOEServer.exe',
     'start_args': '',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'myth_of_empires' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'Removi do comando o que o painel nao passa (OutAddress, ServerAdminAccounts, SessionName, '
                  'ShutDownServiceKey, ShutDownServicePort): nome, senha, IP e afins. Acrescente o que faltar.',
                  'O broker recusaria start_args; deixei em branco.']},
    {'appid': 740250,
     'name': 'NeosVR',
     'key': 'neosvr',
     'ports': '',
     'game_port': 0,
     'query_port': 0,
     'extra_port': 0,
     'start_script': '',
     'start_args': '',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'neosvr' do Pterodactyl: confira antes de enviar.",
                  'O README do egg nao lista a porta padrao: preencha as portas.',
                  "O egg sobe o jogo por 'mono', que o broker nao chama: preencha o script de start e os "
                  'argumentos a mao.']},
    {'appid': 1420710,
     'name': 'Night Of The Dead',
     'key': 'night-of-the-dead',
     'ports': '27015/udp 27016/udp',
     'game_port': 27015,
     'query_port': 27016,
     'extra_port': 0,
     'start_script': 'LF/Binaries/Win64/LFServer-Win64-Shipping.exe',
     'start_args': '?listen -Port={PORT} -QueryPort={QUERY_PORT} -console -log',
     'shiftable': True,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '/opt/game/LF/Saved/Config',
     'config_files': ['/opt/game/LF/Saved/Config/ServerSettings.ini'],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'night_of_the_dead' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'Removi do comando o que o painel nao passa (CRASHREPORTS): nome, senha, IP e afins. '
                  'Acrescente o que faltar.']},
    {'appid': 3796810,
     'name': 'Nightingale',
     'key': 'nightingale',
     'ports': '7777/udp',
     'game_port': 7777,
     'query_port': 0,
     'extra_port': 0,
     'start_script': '',
     'start_args': '',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'nightingale' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'O egg nao diz qual e o executavel: preencha o script de start.']},
    {'appid': 2833050,
     'name': 'No Love Lost',
     'key': 'no-love-lost',
     'ports': '7777/udp 27015/udp',
     'game_port': 7777,
     'query_port': 27015,
     'extra_port': 0,
     'start_script': 'NoLoveLost/Binaries/Win64/NoLoveLostServer-Win64-Shipping.exe',
     'start_args': '-port={PORT} -queryport=27016 -log',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'no_love_lost' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'Removi do comando o que o painel nao passa (servername): nome, senha, IP e afins. Acrescente '
                  'o que faltar.']},
    {'appid': 2329680,
     'name': 'No One Survived',
     'key': 'no-one-survived',
     'ports': '5761/udp 27015/udp',
     'game_port': 5761,
     'query_port': 27015,
     'extra_port': 0,
     'start_script': 'WRSHServer.exe',
     'start_args': '-server -log -Port={PORT} -QueryPort={QUERY_PORT}',
     'shiftable': True,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '/opt/game/WRSH/Saved/Config/WindowsServer',
     'config_files': ['/opt/game/WRSH/Saved/Config/WindowsServer/Engine.ini',
                      '/opt/game/WRSH/Saved/Config/WindowsServer/Game.ini'],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'no_one_survived' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.']},
    {'appid': 1665030,
     'name': 'Nova-Life: Amboise',
     'key': 'nova-life-amboise',
     'ports': '7777/udp',
     'game_port': 7777,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'nova-life.x86_64',
     'start_args': '-batchmode -nographics',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'novalife_amboise' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Removi do comando o que o painel nao passa (startServer): nome, senha, IP e afins. Acrescente '
                  'o que faltar.']},
    {'appid': 824360,
     'name': 'PixARK',
     'key': 'pixark',
     'ports': '27015/udp 27016/udp 27018/udp',
     'game_port': 27015,
     'query_port': 27016,
     'extra_port': 27018,
     'start_script': 'ShooterGame/Binaries/Win64/PixARKServer.exe',
     'start_args': '-Seed=12345 -OreSeed=1234 -ConfigsUseAltDir -server -gameplaylogging -log '
                   '-CULTUREFORCOOKING=en -NoBattlEye -Port={PORT} -nosteamclient -NoHangDetection',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'pixark' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'Removi do comando o que o painel nao passa (CubePort, QueryPort, cubeworld): nome, senha, IP '
                  'e afins. Acrescente o que faltar.']},
    {'appid': 374040,
     'name': 'Portal Knights',
     'key': 'portal-knights',
     'ports': '16365/udp',
     'game_port': 16365,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'dedicated_server/pk_dedicated_server.exe',
     'start_args': '-config server_config.json -log server.log',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton', 'xvfb'],
     'config_path': '/opt/game/dedicated_server',
     'config_files': ['/opt/game/dedicated_server/server_config.json'],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'portal_knights' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.']},
    {'appid': 3481440,
     'name': 'Puck',
     'key': 'puck',
     'ports': '7777/udp 7778/udp',
     'game_port': 7777,
     'query_port': 0,
     'extra_port': 7778,
     'start_script': 'Puck.x86_64',
     'start_args': '',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '/opt/game',
     'config_files': ['/opt/game/server_configuration.json'],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'puck' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.']},
    {'appid': 1652070,
     'name': 'QANGA',
     'key': 'qanga',
     'ports': '10000/udp 27016/udp',
     'game_port': 10000,
     'query_port': 27016,
     'extra_port': 0,
     'start_script': 'Qanga/Binaries/Linux/QangaServer-Linux-Shipping',
     'start_args': 'Qanga /Game/Maps/Universe/L_Persistent_Universe? -server -log -port={PORT} '
                   '-map=L_Persistent_Universe -QueryPort={QUERY_PORT}',
     'shiftable': True,
     'platform': '',
     'recipes': [],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'qanga' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Removi do comando o que o painel nao passa (sessionName): nome, senha, IP e afins. Acrescente '
                  'o que faltar.']},
    {'appid': 2519830,
     'name': 'Resonite',
     'key': 'resonite',
     'ports': '',
     'game_port': 0,
     'query_port': 0,
     'extra_port': 0,
     'start_script': '',
     'start_args': '',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'resonite' do Pterodactyl: confira antes de enviar.",
                  'O README do egg nao lista a porta padrao: preencha as portas.',
                  "O egg sobe o jogo por 'dotnet', que o broker nao chama: preencha o script de start e os "
                  'argumentos a mao.']},
    {'appid': 1180760,
     'name': 'Risk of Rain 2',
     'key': 'risk-of-rain-2',
     'ports': '27015/udp 27016/udp 27017/udp',
     'game_port': 27015,
     'query_port': 27016,
     'extra_port': 27017,
     'start_script': '',
     'start_args': '',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton', 'xvfb'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'risk_of_rain_2' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'O executavel do egg (./Risk of Rain 2.exe) nao cabe no broker: preencha o script de start.']},
    {'appid': 808040,
     'name': 'Smalland: Survive the Wilds',
     'key': 'smalland-survive-the-wil',
     'ports': '7777/udp',
     'game_port': 7777,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'SMALLAND/Binaries/Linux/SMALLANDServer-Linux-Shipping',
     'start_args': 'SMALLAND',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'smalland_survive_the_wilds' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'O comando do egg encadeava outros comandos (;, |, &&): so o do jogo ficou.']},
    {'appid': 1086950,
     'name': 'Solace Crafting',
     'key': 'solace-crafting',
     'ports': '27015/udp 27016/udp',
     'game_port': 27015,
     'query_port': 27016,
     'extra_port': 0,
     'start_script': '',
     'start_args': '',
     'shiftable': False,
     'platform': '',
     'recipes': [],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'solace_crafting' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'O executavel do egg (./Solace Crafting.x86_64) nao cabe no broker: preencha o script de '
                  'start.']},
    {'appid': 298740,
     'name': 'Space Engineers',
     'key': 'space-engineers',
     'ports': '27016/udp 8766/udp',
     'game_port': 27016,
     'query_port': 0,
     'extra_port': 8766,
     'start_script': 'DedicatedServer64/SpaceEngineersDedicated.exe',
     'start_args': '-console -ignorelastsession',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '/opt/game/config',
     'config_files': ['/opt/game/config/SpaceEngineers-Dedicated.cfg'],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'space_engineers/default' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'Removi do comando o que o painel nao passa (path): nome, senha, IP e afins. Acrescente o que '
                  'faltar.']},
    {'appid': 1247090,
     'name': 'Stormworks: Build and Rescue',
     'key': 'stormworks-build-and-res',
     'ports': '25564/udp 25565/udp 25566/udp',
     'game_port': 25564,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'server64.exe',
     'start_args': '+server_dir /opt/game/server_data',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton', 'xvfb'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'stormworks' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.']},
    {'appid': 2058450,
     'name': "Swords 'n Magic and Stuff",
     'key': 'swords-n-magic-and-stuff',
     'ports': '7777/udp 27015/udp',
     'game_port': 7777,
     'query_port': 27015,
     'extra_port': 0,
     'start_script': 'SNM2020/Binaries/Win64/SNMASServer-Win64-Shipping.exe',
     'start_args': '-port={PORT} -QueryPort={QUERY_PORT} -log',
     'shiftable': True,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'swords_'n_Magic_and_Stuff' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.']},
    {'appid': 2533070,
     'name': 'TerraTech Worlds',
     'key': 'terratech-worlds',
     'ports': '7777/udp',
     'game_port': 7777,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'TT2/Binaries/Win64/TT2Server-Win64-Shipping.exe',
     'start_args': '-log',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '/opt/game',
     'config_files': ['/opt/game/dedicated_server_config.json'],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'terratech_worlds' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.']},
    {'appid': 507320,
     'name': 'The Bus',
     'key': 'the-bus',
     'ports': '7778/udp',
     'game_port': 7778,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'TheBus/Binaries/Linux/TheBusServer_Linux',
     'start_args': '-log -newconsole -useperfthreads -port={PORT}',
     'shiftable': True,
     'platform': '',
     'recipes': [],
     'config_path': '/opt/game/TheBus/Settings',
     'config_files': ['/opt/game/TheBus/Settings/ServerSettings.cfg'],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'the_bus' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.']},
    {'appid': 556450,
     'name': 'The Forest',
     'key': 'the-forest',
     'ports': '',
     'game_port': 0,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'TheForestDedicatedServer.exe',
     'start_args': '-batchmode -nographics -inittype New -nosteamclient -savefolderpath '
                   '/opt/game/TheForestDedicatedServer_Data -configfilepath '
                   '/opt/game/TheForestDedicatedServer_Data/forest/config/config.cfg',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton', 'xvfb'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'the_forest' do Pterodactyl: confira antes de enviar.",
                  'O README do egg nao lista a porta padrao: preencha as portas.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'Removi do comando o que o painel nao passa (serverPasswordAdmin): nome, senha, IP e afins. '
                  'Acrescente o que faltar.']},
    {'appid': 3349480,
     'name': 'The Lord of the Rings: Return to Moria',
     'key': 'the-lord-of-the-rings-re',
     'ports': '7777/udp 7777/tcp',
     'game_port': 7777,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'Moria/Binaries/Win64/MoriaServer-Win64-Shipping.exe',
     'start_args': '',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton', 'xvfb'],
     'config_path': '/opt/game',
     'config_files': ['/opt/game/MoriaServerConfig.ini'],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'lotr_moria' do Pterodactyl: confira antes de enviar.",
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.']},
    {'appid': 2403,
     'name': 'The Ship: Murder Party',
     'key': 'the-ship-murder-party',
     'ports': '27015/udp',
     'game_port': 27015,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'srcds.exe',
     'start_args': '-console -condebug -conclearlog -game ship +log on +map batavier +maxplayers 8 -port {PORT} '
                   '+ip 0.0.0.0 -strictportbind',
     'shiftable': True,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'the_ship' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.']},
    {'appid': 2131400,
     'name': 'VEIN',
     'key': 'vein',
     'ports': '7777/udp 27015/udp',
     'game_port': 7777,
     'query_port': 27015,
     'extra_port': 0,
     'start_script': 'Vein/Binaries/Linux/VeinServer-Linux-Test',
     'start_args': '-Port={PORT} -QueryPort={QUERY_PORT} -log',
     'shiftable': True,
     'platform': '',
     'recipes': [],
     'config_path': '/opt/game/Vein/Saved/Config/LinuxServer',
     'config_files': ['/opt/game/Vein/Saved/Config/LinuxServer/Game.ini'],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'vein' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.']},
    {'appid': 3937860,
     'name': 'Voyagers of Nera',
     'key': 'voyagers-of-nera',
     'ports': '27700/udp 27701/udp',
     'game_port': 27700,
     'query_port': 0,
     'extra_port': 27701,
     'start_script': '',
     'start_args': '',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '/opt/game/Saved/PersistedData/CustomConfig',
     'config_files': ['/opt/game/Saved/PersistedData/CustomConfig/CustomHostServerUserSettings.ini'],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'voyagers_of_nera' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'O egg nao diz qual e o executavel: preencha o script de start.']},
    {'appid': 3519390,
     'name': 'Wreckfest 2',
     'key': 'wreckfest-2',
     'ports': '',
     'game_port': 0,
     'query_port': 0,
     'extra_port': 0,
     'start_script': 'Wreckfest2.exe',
     'start_args': '--server',
     'shiftable': False,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '',
     'config_files': [],
     'backup_paths': [],
     'player_source': 'log',
     'warnings': ["Tirado do egg 'wreckfest_2' do Pterodactyl: confira antes de enviar.",
                  'O README do egg nao lista a porta padrao: preencha as portas.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.',
                  'Removi do comando o que o painel nao passa (save-dir): nome, senha, IP e afins. Acrescente o '
                  'que faltar.',
                  'O comando do egg encadeava outros comandos (;, |, &&): so o do jogo ficou.']},
    {'appid': 2536350,
     'name': 'Zombie Survival Game Online',
     'key': 'zombie-survival-game-onl',
     'ports': '26900/udp 27015/udp',
     'game_port': 26900,
     'query_port': 27015,
     'extra_port': 0,
     'start_script': 'ZSGO/Binaries/Win64/ZSGOServer-Win64-Shipping.exe',
     'start_args': '-server -log -port={PORT} -queryport={QUERY_PORT} -multihome=0.0.0.0',
     'shiftable': True,
     'platform': 'windows',
     'recipes': ['proton'],
     'config_path': '/opt/game/ZSGO/Content/DedicatedServer',
     'config_files': ['/opt/game/ZSGO/Content/DedicatedServer/ServerConfig.json'],
     'backup_paths': [],
     'player_source': 'a2s',
     'warnings': ["Tirado do egg 'zombie_survival_game_online' do Pterodactyl: confira antes de enviar.",
                  'O egg nao diz o protocolo das portas: presumi UDP, o de todo jogo Steam.',
                  'Servidor so de Windows: roda pelo Proton (receita proton). Se nao subir, troque para wine.']},
)

COMPLEMENTS: dict[int, dict] = {232130: {'config_files': ['/opt/game/KFGame/Config/KFWeb.ini',
                           '/opt/game/KFGame/Config/LinuxServer-KFGame.ini'],
          'config_path': '/opt/game/KFGame/Config'},
 258550: {'config_files': ['/opt/game/server/rust/cfg/server.cfg'],
          'config_path': '/opt/game/server/rust/cfg'},
 276060: {'config_files': ['/opt/game/svencoop/server.cfg']},
 302550: {'config_files': ['/opt/game/cfg/server_cfg.ini']},
 343050: {'config_files': ['/opt/game/DoNotStarveTogether/config/server/cluster.ini',
                           '/opt/game/DoNotStarveTogether/config/server/Master/server.ini',
                           '/opt/game/DoNotStarveTogether/config/server/Caves/server.ini'],
          'config_path': '/opt/game/DoNotStarveTogether/config/server'},
 402370: {'config_files': ['/opt/game/LaunchConfig.ini'], 'config_path': '/opt/game'},
 439660: {'config_files': ['/opt/game/Tower/Saved/Config/LinuxServer/TowerServer.ini']},
 1874900: {'config_files': ['/opt/game/config.json']}}
