#!/usr/bin/env python3
"""Game search by name or App ID, to fill in the "Add game" form.

Reads three lists, all in the repository: `suggestions.py` (generated by tools/import-linuxgsm.py),
`manual_suggestions.py` (written by hand, for the Windows-only servers reviewed here) and
`pterodactyl_suggestions.py` (generated by tools/import-pterodactyl.py from the Pterodactyl eggs:
the games the others do not have, and the fields missing from a LinuxGSM suggestion). The panel
in production queries nothing on the internet, so there is no SSRF and no third-party dependency
at run time. Pure like `navigation.py`: no Flask, no database.

The result is a SUGGESTION. The broker is what validates it when the form is submitted.
"""
from __future__ import annotations

import re
import unicodedata
from collections.abc import Callable

from gamepanel import i18n
from gamepanel.games.catalog import manual_suggestions, pterodactyl_suggestions
from gamepanel.games.catalog import suggestions as sugestoes_de_jogos

# `translate(key, **fields)`: the blueprint passes the one of the request (the person's language).
# Translating at import would freeze the deploy language into every warning.
Translate = Callable[..., str]

_COMBINED_SOURCE = f"{sugestoes_de_jogos.SOURCE.split(',')[0]} + {pterodactyl_suggestions.SOURCE.split(',')[0]}"
# The label of each field the egg fills in (i18n keys), so the warning says WHAT came from there.
_FIELD_LABELS = {"config_path": "catalog.suggestion.field.config_path",
                 "config_files": "catalog.suggestion.field.config_files",
                 "ports": "catalog.suggestion.field.ports"}


def _deploy_language(key: str, **fields: object) -> str:
    return i18n.translate(key, i18n.DEFAULT, **fields)


def source_text(translate: Translate = _deploy_language) -> str:
    """Every source of the search, in one line. The manual list's source is a catalog key; the
    generated ones (LinuxGSM, Pterodactyl) are data and pass through `translate` unchanged."""
    return "; ".join(translate(s) for s in (sugestoes_de_jogos.SOURCE, manual_suggestions.SOURCE,
                                              pterodactyl_suggestions.SOURCE))
DEFAULT_LIMIT = 8
QUERY_MAX = 60


def _normalize(text: str) -> str:
    """No accents, lowercase, only letters and digits: 'Counter-Strike' matches 'counter strike'."""
    without_accents = unicodedata.normalize("NFKD", text).encode("ascii", "ignore").decode()
    return re.sub(r"[^a-z0-9]+", " ", without_accents.lower()).strip()


def _with_complement(s: dict) -> tuple[dict, str]:
    """The LinuxGSM suggestion with the EMPTY fields the egg fills in. The merge already went through
    the broker validator at generation time (the panel does not have the broker to validate here).
    Which fields came from the egg is noted in `_COMPLEMENTED`, and `result` turns it into the warning
    in the language of whoever asked."""
    extra = pterodactyl_suggestions.COMPLEMENTS.get(s["appid"])
    if not extra:
        return s, sugestoes_de_jogos.SOURCE
    merged = {**s, **extra}
    _COMPLEMENTED[id(merged)] = tuple(_FIELD_LABELS[k] for k in extra if k in _FIELD_LABELS)
    return merged, _COMBINED_SOURCE


# id(suggestion) -> label keys of the fields the Pterodactyl egg filled in.
_COMPLEMENTED: dict[int, tuple[str, ...]] = {}


# The source of each suggestion goes along, and the screen shows it: "LinuxGSM", "panel curation"
# and "Pterodactyl" are different degrees of trust, and whoever reviews needs to know which one
# they are looking at. No App ID shows up in two lists (the tests check): whoever generates the
# Pterodactyl one skips what the others already have.
_ALL = (tuple(_with_complement(s) for s in sugestoes_de_jogos.SUGGESTIONS)
        + tuple((s, manual_suggestions.SOURCE) for s in manual_suggestions.SUGGESTIONS)
        + tuple((s, pterodactyl_suggestions.SOURCE) for s in pterodactyl_suggestions.SUGGESTIONS))
_SOURCE_OF = {id(s): source for s, source in _ALL}
_INDEX = tuple((s, _normalize(f"{s['name']} {s['key']}")) for s, _ in _ALL)


def search(query: str | None, limit: int = DEFAULT_LIMIT) -> list[dict]:
    """A bare number = exact App ID. Text = all words appear in the name; those that START
    with the first word come first ('pal' finds Palworld before 'Space Pals')."""
    q = (query or "").strip()[:QUERY_MAX]
    if not q:
        return []
    if q.isdigit():
        return [s for s, _ in _ALL if str(s["appid"]) == q][:limit]
    terms = _normalize(q).split()
    if not terms:
        return []
    found = [(s, text) for s, text in _INDEX if all(t in text for t in terms)]
    # `str(...)`: each suggestion is a `dict` of mixed values (App ID number, name text),
    # so for the type checker `s["name"]` is `object`. The `str` says what this field IS,
    # instead of scattering `cast` over the two sorting lines.
    found.sort(key=lambda par: (not _normalize(str(par[0]["name"])).startswith(terms[0]),
                                  str(par[0]["name"]).lower()))
    return [s for s, _ in found[:limit]]


def to_form(s: dict) -> dict[str, str]:
    """The values under the keys that are the fields' `name=`. ALL keys always, even empty:
    picking another game has to clear what the previous one left (script, ports, the config
    folder and the log pattern of a game that is not this one)."""
    return {
        "key": s["key"], "name": s["name"], "app_id": str(s["appid"]),
        "ports": s["ports"], "game_port": str(s["game_port"] or ""),
        "query_port": str(s["query_port"] or ""), "extra_port": str(s.get("extra_port") or ""),
        "start_script": s["start_script"], "start_args": s["start_args"],
        "shiftable": "1" if s["shiftable"] else "",
        "config_path": s.get("config_path", ""),
        "config_files": "\n".join(s.get("config_files") or []),
        "player_source": s.get("player_source") or "log",
        # LinuxGSM does not say where the save is, what the log writes nor how much machine
        # the game needs: it stays blank, and not with what was left from the previously
        # chosen game. The manual list does say, and then it goes.
        "backup_paths": "\n".join(s.get("backup_paths") or []),
        "join_re": s.get("join_re", ""), "leave_re": s.get("leave_re", ""),
        "memory_mb": str(s.get("memory_mb") or ""), "cores": str(s.get("cores") or ""),
        "disk_gb": str(s.get("disk_gb") or ""),
        # A LinuxGSM game is always Linux: empty platform and recipes CLEAR the Windows and
        # Proton of a previous suggestion, which would turn into a Wine install for no reason.
        "platform": s.get("platform", ""), "recipes": " ".join(s.get("recipes") or []),
    }


def result(s: dict, translate: Translate = _deploy_language) -> dict:
    """What the API sends. The manual list's warnings and source are catalog keys; the generated
    lists' are data (LinuxGSM/Pterodactyl), and `translate` gives an unknown key back as is."""
    warnings = [translate(w) for w in s["warnings"]]
    labels = _COMPLEMENTED.get(id(s))
    if labels:
        fields = ", ".join(sorted(translate(k) for k in labels))
        warnings.append(translate("catalog.suggestion.from_pterodactyl", fields=fields))
    return {"appid": s["appid"], "name": s["name"], "values": to_form(s),
            "warnings": warnings, "source": translate(_SOURCE_OF.get(id(s), ""))}
